### ISSUE TITLE
bug: 400 bad request when trying to refresh access token

### ISSUE THREAD

**Issue by ikupenov** [logto-io/js#527] opened 2023-07-13 09:54 UTC
### Describe the bug
Trying to refresh the access token using `https://admin.logto.com/oidc/token` results in 400 bad request, presumably when the refresh token has expired (not sure about this). This happens when using the admin dashboard and when using the client JS SDK in my own client-facing app. Right now, when the access token fails to refresh, I have to manually clear the app cache so I can forcefully relog.

**Request:**
```
curl 'https://admin.logto.com/oidc/token' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-US,en;q=0.9,bg;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'DNT: 1' \
  -H 'Origin: https://admin.logto.com' \
  -H 'Referer: https://admin.logtom.com/console/dashboard' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw 'client_id=admin-console&refresh_token=T_o50kWn-OWjVjyvaM0y_ZDlALMg651_u4GEtZOwf60&grant_type=refresh_token&resource=https%3A%2F%2Fadmin.logto.app%2Fme' \
  --compressed
```

**Response:**

`{"error":"invalid_grant","error_description":"grant request is invalid"}`

### Expected behavior
The access token should be refreshed successfully or the user should be redirected to the login page.

### How to reproduce?
Not sure.

### Context

- [ ] Logto Cloud
- [X] Self-hosted, Logto version = Logto version = 1.5, @logto/browser = 2.1.0
  - [X] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots

<img width="1338" alt="CleanShot 2023-07-13 at 12 41 51@2x" src="https://github.com/logto-io/js/assets/13287035/e9afc908-543f-4a33-95ba-fd3afbf122dc">

**Comment by charIeszhao** [comment] 2023-07-18 08:15
How did you "refresh your access token" in the first place? Did you implement your own code or just simply called `getAccessToken()` provided by SDK?

**Comment by ikupenov** [comment] 2023-07-18 18:08
No custom code at all, just calling `getAccessToken()` as shown in the docs.

**Comment by charIeszhao** [comment] 2023-07-19 05:22
Hmmm, after reading the post carefully I think it was an acknowledged bug that we fixed in OSS v1.6.0.

Previously there was an issue (fixed in #520) with the React SDK that would cause a loop when exchanging access tokens with a prefresh token.

There were also bug fixes on the admin console side that improved the error handling, including showing a re-login button when refresh token expires instead of just showing the error message.

So can you just upgrade to 1.6 and give it another try? Let me know if you are still able to reproduce the issue.

Thanks.

**Comment by ikupenov** [comment] 2023-07-19 09:49
I'm on the latest SDK version but I'll update to the latest Docker image and let you know. However, I think the client-side SDK doesn't handle the case where the refresh token has expired so it returns the response mentioned above. That's my workaround right now:

<img width="709" alt="CleanShot 2023-07-19 at 12 47 19@2x" src="https://github.com/logto-io/js/assets/13287035/54abd01b-3e5d-4ead-bfbc-95d0a8d9af1a">

**Comment by charIeszhao** [comment] 2023-07-19 12:48
You are right that we don't handle the case when the refresh token expires. That's because it's up to the SDK user to decide what to do next. You can either sign out and navigate back to home page, or automatically sign in again. We can't decide on behalf of our users but only return an error instead.

Your code looks good, and I think you don't need to clear the local storage yourself but instead just call the `signIn` function from logto client again.

As for the refresh token lifetime, we used to have that input box in the application details page, but for some reason we removed that from the UI months ago. I believe you can still do that through calling the application API, though. I will ask the team if anyone has more context about this change, and update you later.

**Comment by ikupenov** [comment] 2023-07-19 14:43
> You are right that we don't handle the case when the refresh token expires. That's because it's up to the SDK user to decide what to do next. You can either sign out and navigate back to home page, or automatically sign in again. We can't decide on behalf of our users but only return an error instead.

Okay, fair enough. Might be a good idea to include it in the docs because it took me some time to find out what the issue was.

> As for the refresh token lifetime, we used to have that input box in the application details page, but for some reason we removed that from the UI months ago. I believe you can still do that through calling the application API, though. I will ask the team if anyone has more context about this change, and update you later.

Tried to patch the application by settings `rotateRefreshToken` and `refreshTokenTtlInDays` but it seems they are not being picked up when the application type is SPA. 😕

**Comment by ikupenov** [comment] 2023-07-25 09:34
While on a similar topic, I'd like to suggest having the access token lifetime configurable as well.

**Comment by charIeszhao** [comment] 2023-07-25 10:36
I have created a [pull request](https://github.com/logto-io/logto/pull/4232) to allow editing refresh token TTL for SPA applications.
As for configuring access token TTL, you can go to "API Resources" and change the settings there.

**Comment by ikupenov** [comment] 2023-07-25 15:53
Ah right, that's perfect, thank you!

**Comment by charIeszhao** [comment] 2023-07-26 03:16
You're welcome. The refresh token TTL will be able to be configured in admin console in the next release.

Cheers

**Closed** 2023-07-26 14:07 UTC
Labels: enhancement
