### ISSUE TITLE
bug: isAuthenticated is always FALSE when signin by a user

### ISSUE THREAD

**Issue by mrkirthi-24** [logto-io/js#849] opened 2024-11-15 07:22 UTC
### Describe the bug

I am using "@tanstack/react-query": "^5.59.20", "@tanstack/react-router": "^1.81.1" in my react project. When a user does a sign in, it is redirected to callback page but, isAuthenticated is always FALSE.

### Expected behavior

isAuthenticated needs to be TRUE.

### Context

I am using Logto React SDK. here useHandleSignInCallback is not returning me true.

`import { createFileRoute } from '@tanstack/react-router';
import { useHandleSignInCallback } from '@logto/react';
import { useNavigate } from '@tanstack/react-router';

export const Route = createFileRoute('/signin/callback')({
  component: Callback,
});

function Callback() {
  // const navigate = useNavigate(); // Get the navigate function from TanStack Router
  const { isLoading, isAuthenticated, error } = useHandleSignInCallback( () => {
    // console.log("Callback handled, navigating to home");
    alert("Callback handled, navigating to home");
    window.location.href = '/'; // This will reload the page
  });

  console.log("isLoading:", isLoading);
  console.log("error:", error);
  console.log("isAuthenticated:", isAuthenticated);

  // If it's loading, show a loading state
  if (isLoading) {
    return <div>Redirecting...</div>;
  }

  // If there's an error, show an error message
  if (error) {
    return <div>Error: {error}</div>;
  }

  return <div>callback page loaded</div>
}

export default Callback;`

- [ ] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

<img width="1440" alt="Screenshot 2024-11-15 at 12 48 19 PM" src="https://github.com/user-attachments/assets/2ad6cbaf-8151-4ddd-87e3-00c9e95db9d7">

<img width="1440" alt="Screenshot 2024-11-15 at 12 48 59 PM" src="https://github.com/user-attachments/assets/5cb4b2f5-56ee-4d60-9aa6-64c0cadd4e23">

<img width="1440" alt="Screenshot 2024-11-15 at 12 50 14 PM" src="https://github.com/user-attachments/assets/7cfd96e6-8ae5-4c7b-b1b5-05de60b3fc29">

**Comment by charIeszhao** [comment] 2024-11-15 09:04
This is because when you do `console.log(isAuthenticated)`, the `useHandleSignInCallback` hook is not completed yet...

The `isAuthenticated` will be true if you have ID token issued from the auth server.

**Comment by wangsijie** [comment] 2024-11-18 01:02
duplicate of https://github.com/logto-io/js/issues/835

**Comment by mrkirthi-24** [comment] 2024-11-18 04:17
thanks @charIeszhao. The issue is solved

**Closed** 2024-11-20 14:05 UTC
