### ISSUE TITLE
bug: refresh token not found

### ISSUE THREAD

**Issue by Joozty** [logto-io/js#684] opened 2024-04-06 10:41 UTC
### Describe the bug

I'm using the `@logto/next` package to integrate logto.io with my Next.js application (app router). I followed the documentation you provided, and everything worked until now. I haven't worked on the project for a week, and today, when I use the `logtoClient.getLogtoContext` method, I receive an `invalid_grant` error. I checked the audit logs and found out that the refresh token is not found (see attached screenshot). This error is only thrown when I use `fetchUserInfo: true`. If this is omitted, the context is correctly returned with `isAuthenticated` set to true. Can you please guide me on what to do in this case? Is it a bug on your side?

### Expected behavior
User info is fetched correctly when `fetchUserInfo` is set to true.

### Context

- [x] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots

Fetch info is set to true - throws `invalid_grant` error.
![image](https://github.com/logto-io/js/assets/12775440/71cd7fd7-841f-4bff-8d4f-dc395d5d5054)

Fetch info is set to false - works correctly.
![image](https://github.com/logto-io/js/assets/12775440/a7b0bcf1-cb90-4c82-939f-45cdb0a9c5e4)

Audit log error
![image](https://github.com/logto-io/js/assets/12775440/d7e0fb17-365c-4df2-a4ef-5837bcc38a00)

**Comment by wangsijie** [comment] 2024-04-07 00:56
Event the refresh token is expired, the error message won't be "refresh token not found". I guess the problem is on the user side, maybe this user is deleted or suspended?

**Comment by Joozty** [comment] 2024-04-07 07:46
The user is neither suspended nor deleted. I managed to log out and log back in again, and everything works just fine. However, I am worried that this issue might occur in production and I would like to known how to handle it correctly.

**Comment by wangsijie** [comment] 2024-04-08 01:46
I will review the logs and attempt to reproduce. I’ll keep you posted on this issue.

**Comment by wangsijie** [comment] 2024-04-17 07:17
I am unable to reproduce, I started a project, sign in, and wait for several days, make sure the refresh token is already expired. Then try to fetch user info, the error message is "grant request is invalid" which is expected.

Though, there is one thing to do, make sure the cookie expiration time is shorter then refresh token TTL.

I am closing this issue, feel free to reopen if it happens again.

**Closed by wangsijie** 2024-04-17 07:17 UTC
Labels: bug
